version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api-c
    expose: 
      - 9090
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3090:80"